import type { Locale } from "@/lib/i18n";

const copy = {
  en: {
    title: "Track CSA request",
    intro:
      "Enter your request code and the phone number used to register to view its status.",
    referenceCode: "Request or contract code",
    referencePlaceholder: "CSA-XXXXXXXXXXXX",
    phone: "Phone number",
    phonePlaceholder: "0901234567",
    lookup: "Look up",
    lookingUp: "Looking up…",
    tryAgain: "Try again",
    returnToForm: "Return to lookup form",
    required: "Please complete this field.",
    invalidPhone: "Enter a valid Vietnamese phone number.",
    lookupUnavailable: "We could not find a request with this information.",
    sessionExpired:
      "Your secure lookup session has expired. Enter the code and phone number again.",
    contractUnavailable: "The contract is not available for this request.",
    loadingContract: "Loading contract…",
    retryContract: "Retry loading contract",
    pdfUnavailable: "The contract PDF is temporarily unavailable.",
    invalidLocale: "This PDF language is not available.",
    rateLimited: "Too many attempts. Please wait and try again later.",
    genericError: "We could not complete the lookup. Please try again later.",
    newLookup: "Look up another request",
    statusBadge: "Status",
    requestCode: "Request code",
    contractCode: "Contract code",
    package: "CSA package",
    duration: "Duration",
    durationValue: "{count} month(s)",
    amount: "Amount",
    submittedAt: "Submitted at",
    issuedAt: "Issued at",
    expiredAt: "Expired at",
    rejectedAt: "Rejected at",
    rejectionReason: "Rejection reason",
    startDate: "Start date",
    endDate: "End date",
    contractStatus: "Contract status",
    pending: "Waiting for payment or confirmation",
    paymentConfirmed: "Payment recorded",
    approved: "Approved",
    rejected: "Rejected",
    expired: "Request expired",
    active: "Active",
    revoked: "Revoked",
    refundStatus: "Refund status",
    refundNotApplicable: "Not applicable",
    refundPending: "Pending refund",
    refundCompleted: "Refund completed",
    downloadVi: "Download Vietnamese PDF",
    downloadEn: "Download English PDF",
    downloading: "Downloading…",
    pendingNotice:
      "This request is waiting for payment confirmation before it can be reviewed.",
    paymentConfirmedNotice:
      "Your transfer has been recorded. The admin team is checking the transaction.",
    approvedNotice:
      "Your CSA request has been approved and the contract has been issued.",
    rejectedNotice:
      "This request was not approved. Contact the support team if you need more information.",
    expiredNotice:
      "This request has expired and can no longer be used for payment confirmation.",
  },
  vi: {
    title: "Tra cứu yêu cầu CSA",
    intro: "Nhập mã yêu cầu và số điện thoại đã đăng ký để xem trạng thái.",
    referenceCode: "Mã yêu cầu hoặc mã hợp đồng",
    referencePlaceholder: "CSA-XXXXXXXXXXXX",
    phone: "Số điện thoại",
    phonePlaceholder: "0901234567",
    lookup: "Tra cứu",
    lookingUp: "Đang tra cứu…",
    tryAgain: "Thử lại",
    returnToForm: "Quay lại form tra cứu",
    required: "Vui lòng nhập thông tin này.",
    invalidPhone: "Vui lòng nhập số điện thoại Việt Nam hợp lệ.",
    lookupUnavailable: "Không thể tìm thấy yêu cầu với thông tin này.",
    sessionExpired:
      "Phiên tra cứu an toàn đã hết hạn. Vui lòng nhập lại mã và số điện thoại.",
    contractUnavailable: "Hợp đồng chưa khả dụng cho yêu cầu này.",
    loadingContract: "Đang tải hợp đồng…",
    retryContract: "Thử tải lại hợp đồng",
    pdfUnavailable: "PDF hợp đồng đang tạm thời không khả dụng.",
    invalidLocale: "Ngôn ngữ PDF này không khả dụng.",
    rateLimited: "Bạn thao tác quá nhiều lần. Vui lòng chờ và thử lại sau.",
    genericError: "Không thể hoàn tất tra cứu. Vui lòng thử lại sau.",
    newLookup: "Tra cứu yêu cầu khác",
    statusBadge: "Trạng thái",
    requestCode: "Mã yêu cầu",
    contractCode: "Mã hợp đồng",
    package: "Gói CSA",
    duration: "Thời hạn",
    durationValue: "{count} tháng",
    amount: "Số tiền",
    submittedAt: "Thời gian gửi",
    issuedAt: "Ngày phát hành",
    expiredAt: "Thời gian hết hạn",
    rejectedAt: "Thời gian từ chối",
    rejectionReason: "Lý do từ chối",
    startDate: "Ngày bắt đầu",
    endDate: "Ngày kết thúc",
    contractStatus: "Trạng thái hợp đồng",
    pending: "Đang chờ thanh toán/xác nhận",
    paymentConfirmed: "Đã ghi nhận chuyển khoản",
    approved: "Đã duyệt",
    rejected: "Đã từ chối",
    expired: "Yêu cầu đã hết hạn",
    active: "Đang hoạt động",
    revoked: "Đã thu hồi",
    refundStatus: "Trạng thái hoàn tiền",
    refundNotApplicable: "Chưa áp dụng",
    refundPending: "Chờ hoàn tiền",
    refundCompleted: "Đã hoàn tiền",
    downloadVi: "Tải PDF tiếng Việt",
    downloadEn: "Tải PDF tiếng Anh",
    downloading: "Đang tải…",
    pendingNotice:
      "Yêu cầu đang chờ xác nhận thanh toán trước khi được kiểm tra.",
    paymentConfirmedNotice:
      "Chuyển khoản đã được ghi nhận. Admin đang kiểm tra giao dịch.",
    approvedNotice: "Yêu cầu CSA đã được duyệt và hợp đồng đã được phát hành.",
    rejectedNotice:
      "Yêu cầu chưa được duyệt. Vui lòng liên hệ đội ngũ hỗ trợ nếu cần thêm thông tin.",
    expiredNotice:
      "Yêu cầu đã hết hạn và không thể tiếp tục xác nhận thanh toán.",
  },
} as const;

export function getCSAContractTrackerCopy(locale: Locale) {
  return copy[locale];
}
