import type { Locale } from "@/lib/i18n";

const copy = {
  en: {
    title: "Choose the right package for your family",
    intro:
      "Choose a package, provide the required details, then transfer the exact amount shown.",
    progressLabel: "CSA purchase progress",
    steps: ["Choose package", "Information", "Terms", "Payment"],
    packageStepTitle: "Packages open for registration",
    packageStepDescription: "Choose the package that fits your household.",
    packageProducts: "Products per cycle",
    noPackageProducts: "Product details will be confirmed with this package.",
    registrationDuration: "Registration duration",
    durationColumn: "Duration",
    monthlyPrice: "Monthly price",
    totalPrice: "Total",
    savingPercent: "Save {percent}%",
    savingAmount: "Save {amount} compared with buying monthly",
    monthlyPurchase: "Buying monthly: {amount}",
    durationSaving: "Save: {amount} · {percent}%",
    paymentPlanSaving: "Save {amount} · {percent}%",
    selectionSummary: "Your selection",
    paymentPlanTitle: "Payment method",
    paymentPlanMissing:
      "No valid payment method is available for this duration.",
    paymentPlanRequired:
      "Choose an available payment method before continuing.",
    paymentPlanUnavailable:
      "This payment method is no longer available. Please choose another.",
    payFull: "Pay in full",
    payInstallments: "Pay in {count} installments",
    entirePackage: "Entire package · {count} months",
    packageDuration: "Total package value · {count} months",
    installmentNumber: "Payment {number}",
    installmentBeginning: "{count} months at the beginning",
    installmentFollowing: "{count} following months",
    installmentFinal: "{count} final months",
    cycleCount: "{count} months",
    paymentSchedule: "Payment schedule",
    initialPayment: "First payment to transfer",
    paymentAmountDue: "Amount to transfer",
    packageValue: "Total package value",
    firstPaymentCycles: "Months unlocked by the first payment",
    summaryMethod: "Payment method",
    summaryFirstPayment: "First payment",
    summaryAmountDue: "Amount due",
    initialPaymentMissing:
      "The first payment amount is unavailable. Please contact Natural Farming Vietnam before transferring money.",
    paymentSnapshotInvalid:
      "Payment details could not be verified. Please contact Natural Farming Vietnam before transferring money.",
    startDateNote:
      "The start date will be confirmed after payment and the existing package schedule are checked.",
    informationStepTitle: "Your information",
    informationStepDescription:
      "Provide the details needed to process your request.",
    loadingAccount: "Loading account information…",
    termsStepTitle: "How the program works",
    termsStepDescription:
      "By checking each box, I confirm that I have read, fully understood, and agree to each item below.",
    previous: "Back",
    next: "Continue",
    packagesLoading: "Loading available packages…",
    packagesEmpty: "There are no CSA packages available right now.",
    packagesError: "We could not load CSA packages. Please try again.",
    retry: "Try again",
    duration: "{count} month(s)",
    signedInNote:
      "Your name, phone number and address will be taken securely from Auth Account.",
    name: "Full name",
    nameHint: "Enter your full name as it should appear on the contract.",
    email: "Email",
    phone: "Phone number",
    phoneHint: "0987654321",
    province: "Province / city",
    ward: "Ward / commune",
    address: "Detailed address",
    addressHint:
      "Include house number, street/hamlet and any delivery details.",
    selectProvince: "Select a province or city",
    selectWard: "Select a ward or commune",
    wardsLoading: "Loading wards…",
    required: "Please complete this field.",
    invalidPhone: "Enter a valid Vietnamese phone number.",
    terms: {
      items: [
        "Naturally farmed — grown with no pesticides, herbicides, or fungicides; fertilized with fermented organic inputs; pests managed with beneficial insects, crop rotation, and healthy soil.",
        "Each week I choose from that week's CSA list (items marked “|C”). The list shows only what's ready, so nothing I pick is out of stock.",
        "I can mix any of the three groups — leafy greens; herbs; and roots, fruits & vegetables — up to my plan's limit per group (1 person: 10 · 2–3 people: 20 · 4–7 people: 30 items per group, each week).",
        "What's offered changes each week with the season, weather, and harvest.",
        "If something runs low, the farm may substitute an equally fresh item and will let me know first.",
        "My share is delivered free to my registered address every Friday, within 24 hours of harvest, roughly 8:00–18:00. I will stay reachable on delivery day; if I cannot be reached, next-day delivery and product quality are my responsibility. The farm is not liable for third-party courier problems but will help resolve them.",
        "I can skip or pause a week (for example, when traveling) by telling the farm in advance.",
        "The farm contacts me mainly by Zalo/WhatsApp, and posts each week's available crops on the website. I will report any change to my address or contact details, and I am welcome to send feedback anytime.",
        "I agree to be added to a group chat of all members on Zalo and/or WhatsApp.",
        "The farm may adjust parts of this agreement (how it grows and delivers) over time, and will notify me before any change.",
        "To the extent permitted by law, I release Natural Farming Vietnam, its owner, agents, and employees from liability for claims or damages relating to farm property, delivery/pickup, or my membership.",
      ],
    },
    termsCheckAll: "Check all",
    termsRequired: "Please tick every agreement checkbox before continuing.",
    continue: "Continue to payment",
    creating: "Creating request…",
    creatingQuote: "Preparing secure payment details…",
    recreateQuote: "Refresh payment details",
    quoteExpired:
      "These payment details have expired. Please create a new request before transferring money.",
    quoteUnavailable:
      "Payment details are unavailable. Please refresh them before transferring money.",
    quoteIdentityMismatch:
      "Your details no longer match this payment quote. Please refresh the payment details.",
    profileIncomplete:
      "Your Auth Account profile is incomplete. Update your name, phone number and address before purchasing CSA.",
    updateAccount: "Update account information",
    paymentTitle: "Transfer payment",
    paymentIntro:
      "Transfer the exact amount with the content below. Do not create another request for this purchase.",
    qrAlt: "VietQR code for CSA bank transfer",
    qrTitle: "QR code",
    bank: "Bank",
    accountNumber: "Account number",
    accountName: "Account name",
    amount: "Amount",
    transferContent: "Transfer content",
    copy: "Copy",
    copied: "Copied",
    confirm: "I have transferred",
    confirming: "Confirming…",
    paymentDataError:
      "Payment information is unavailable. Please contact Natural Farming Vietnam for help.",
    successTitle: "Request submitted",
    success:
      "We have recorded your payment confirmation. You can use the code below to track its status.",
    trackLater: "Track request later",
    packageUnavailable:
      "This package or price option is no longer available. Please choose again.",
    paymentUnavailable:
      "Bank transfer is temporarily unavailable. Please contact our team.",
    duplicate:
      "This phone number already has a purchase request being processed.",
    invalidDetails: "Please check your phone number and address information.",
    notPending: "This request can no longer be confirmed.",
    expired:
      "This purchase request has expired. Please create a new request before transferring money.",
    newRequest: "Start a new request",
    rateLimited: "Too many attempts. Please wait and try again later.",
    genericError: "We could not complete the request. Please try again later.",
  },
  vi: {
    title: "Chọn gói phù hợp cho gia đình",
    intro:
      "Chọn gói, cung cấp thông tin cần thiết rồi chuyển khoản đúng số tiền được hiển thị.",
    progressLabel: "Tiến trình mua CSA",
    steps: ["Chọn gói", "Thông tin", "Điều khoản", "Thanh toán"],
    packageStepTitle: "Gói đang mở đăng ký",
    packageStepDescription:
      "Chọn gói phù hợp với nhu cầu sử dụng của gia đình.",
    packageProducts: "Sản phẩm mỗi kỳ",
    noPackageProducts: "Thông tin sản phẩm sẽ được xác nhận theo gói này.",
    registrationDuration: "Thời hạn đăng ký",
    durationColumn: "Thời hạn",
    monthlyPrice: "Giá theo tháng",
    totalPrice: "Thành tiền",
    savingPercent: "Tiết kiệm {percent}%",
    savingAmount: "Giảm {amount} so với mua từng tháng",
    monthlyPurchase: "Mua từng tháng: {amount}",
    durationSaving: "Tiết kiệm: {amount} · {percent}%",
    paymentPlanSaving: "Tiết kiệm {amount} · {percent}%",
    selectionSummary: "Gói bạn đã chọn",
    paymentPlanTitle: "Phương thức thanh toán",
    paymentPlanMissing: "Thời hạn này chưa có phương thức thanh toán hợp lệ.",
    paymentPlanRequired:
      "Vui lòng chọn phương thức thanh toán trước khi tiếp tục.",
    paymentPlanUnavailable:
      "Phương thức thanh toán này không còn khả dụng. Vui lòng chọn phương thức khác.",
    payFull: "Thanh toán một lần",
    payInstallments: "Trả góp {count} lần",
    entirePackage: "Thanh toán toàn bộ gói · {count} tháng",
    packageDuration: "Tổng giá trị gói · {count} tháng",
    installmentNumber: "Lần {number}",
    installmentBeginning: "{count} tháng đầu",
    installmentFollowing: "{count} tháng tiếp theo",
    installmentFinal: "{count} tháng cuối",
    cycleCount: "{count} tháng",
    paymentSchedule: "Lịch thanh toán",
    initialPayment: "Khoản thanh toán đầu tiên cần chuyển",
    paymentAmountDue: "Số tiền cần chuyển",
    packageValue: "Tổng giá trị gói",
    firstPaymentCycles: "Số tháng được mở sau khoản đầu",
    summaryMethod: "Phương thức",
    summaryFirstPayment: "Khoản thanh toán đầu tiên",
    summaryAmountDue: "Số tiền cần thanh toán",
    initialPaymentMissing:
      "Chưa có số tiền thanh toán đầu tiên. Vui lòng liên hệ Natural Farming Vietnam trước khi chuyển khoản.",
    paymentSnapshotInvalid:
      "Không thể xác minh thông tin thanh toán. Vui lòng liên hệ Natural Farming Vietnam trước khi chuyển khoản.",
    startDateNote:
      "Ngày bắt đầu sẽ được xác nhận sau khi kiểm tra thanh toán và lịch gói hiện có.",
    informationStepTitle: "Thông tin của bạn",
    informationStepDescription:
      "Cung cấp thông tin cần thiết để xử lý yêu cầu.",
    loadingAccount: "Đang tải thông tin tài khoản…",
    termsStepTitle: "Chương trình hoạt động thế nào",
    termsStepDescription:
      "Bằng việc tích vào từng ô, tôi xác nhận đã đọc, hiểu rõ và đồng ý với từng nội dung dưới đây.",
    previous: "Quay lại",
    next: "Tiếp tục",
    packagesLoading: "Đang tải các gói hiện có…",
    packagesEmpty: "Hiện chưa có gói CSA nào khả dụng.",
    packagesError: "Không thể tải danh sách gói CSA. Vui lòng thử lại.",
    retry: "Thử lại",
    duration: "{count} tháng",
    signedInNote:
      "Họ tên, số điện thoại và địa chỉ được lấy an toàn từ Auth Account.",
    name: "Họ tên",
    nameHint: "Nhập đầy đủ họ và tên để ghi trên hợp đồng.",
    email: "Email",
    phone: "Số điện thoại",
    phoneHint: "0987654321",
    province: "Tỉnh/thành phố",
    ward: "Phường/xã",
    address: "Địa chỉ chi tiết",
    addressHint:
      "Nhập số nhà, tên đường/thôn/ấp và thông tin cần thiết để giao hàng.",
    selectProvince: "Chọn tỉnh/thành phố",
    selectWard: "Chọn phường/xã",
    wardsLoading: "Đang tải phường/xã…",
    required: "Vui lòng nhập thông tin này.",
    invalidPhone: "Vui lòng nhập số điện thoại Việt Nam hợp lệ.",
    terms: {
      items: [
        "Canh tác tự nhiên — không dùng thuốc trừ sâu, thuốc diệt cỏ hay thuốc diệt nấm; bón phân từ sản phẩm lên men hữu cơ; kiểm soát sâu bệnh bằng côn trùng có ích, luân canh và quản lý đất hợp lý.",
        "Mỗi tuần tôi chọn từ danh sách CSA của tuần đó (sản phẩm có ký hiệu “|C”). Danh sách chỉ hiển thị những gì đã sẵn sàng, nên món tôi chọn không bao giờ hết hàng.",
        "Tôi có thể phối hợp cả ba nhóm — rau ăn lá; rau thơm; và củ, quả & rau — trong hạn mức mỗi nhóm theo gói (1 người: 10 · 2–3 người: 20 · 4–7 người: 30 món mỗi nhóm, mỗi tuần).",
        "Các loại thực phẩm thay đổi theo tuần, tùy mùa vụ, thời tiết và thu hoạch.",
        "Nếu một món sắp hết, nông trại có thể thay bằng món tươi tương đương và sẽ báo cho tôi trước.",
        "Phần của tôi được giao miễn phí đến địa chỉ đã đăng ký vào mỗi thứ Sáu, trong vòng 24 giờ sau thu hoạch, khoảng 8:00–18:00. Tôi sẽ giữ liên lạc trong ngày giao; nếu không liên lạc được, việc giao và chất lượng sản phẩm ngày hôm sau thuộc trách nhiệm của tôi. Nông trại không chịu trách nhiệm về sự cố từ đơn vị vận chuyển bên thứ ba nhưng sẽ hỗ trợ giải quyết.",
        "Tôi có thể tạm dừng hoặc bỏ qua một tuần (ví dụ khi đi xa) bằng cách báo trước cho nông trại.",
        "Nông trại liên hệ với tôi chủ yếu qua Zalo/WhatsApp, và cập nhật các loại rau có sẵn mỗi tuần trên trang web. Tôi sẽ báo mọi thay đổi về địa chỉ hoặc thông tin liên hệ, và có thể gửi nhận xét bất cứ lúc nào.",
        "Tôi đồng ý được thêm vào nhóm trò chuyện chung của tất cả thành viên trên Zalo và/hoặc WhatsApp.",
        "Nông trại có thể điều chỉnh một số phần của thỏa thuận này (cách trồng và giao hàng) theo thời gian, và sẽ thông báo cho tôi trước khi thay đổi.",
        "Trong phạm vi pháp luật cho phép, tôi miễn trừ trách nhiệm cho Natural Farming Vietnam, chủ sở hữu, đại lý và nhân viên đối với các khiếu nại hay thiệt hại liên quan đến tài sản nông trại, việc giao/nhận hàng, hoặc tư cách thành viên của tôi.",
      ],
    },
    termsCheckAll: "Chọn tất cả",
    termsRequired:
      "Vui lòng đánh dấu tất cả các ô xác nhận trước khi tiếp tục.",
    continue: "Tiếp tục thanh toán",
    creating: "Đang tạo yêu cầu…",
    creatingQuote: "Đang chuẩn bị thông tin thanh toán an toàn…",
    recreateQuote: "Tạo lại thông tin thanh toán",
    quoteExpired:
      "Thông tin thanh toán này đã hết hạn. Vui lòng tạo yêu cầu mới trước khi chuyển khoản.",
    quoteUnavailable:
      "Thông tin thanh toán không khả dụng. Vui lòng tạo lại trước khi chuyển khoản.",
    quoteIdentityMismatch:
      "Thông tin của bạn không còn khớp với báo giá thanh toán. Vui lòng tạo lại thông tin thanh toán.",
    profileIncomplete:
      "Thông tin Auth Account chưa đầy đủ. Vui lòng cập nhật họ tên, số điện thoại và địa chỉ trước khi mua CSA.",
    updateAccount: "Cập nhật thông tin tài khoản",
    paymentTitle: "Thông tin chuyển khoản",
    paymentIntro:
      "Chuyển đúng số tiền và nội dung bên dưới. Không tạo thêm yêu cầu khác cho giao dịch này.",
    qrAlt: "Mã VietQR để chuyển khoản mua CSA",
    qrTitle: "Mã QR",
    bank: "Ngân hàng",
    accountNumber: "Số tài khoản",
    accountName: "Tên chủ tài khoản",
    amount: "Số tiền",
    transferContent: "Nội dung chuyển khoản",
    copy: "Sao chép",
    copied: "Đã sao chép",
    confirm: "Tôi đã chuyển khoản",
    confirming: "Đang xác nhận…",
    paymentDataError:
      "Thông tin thanh toán không khả dụng. Vui lòng liên hệ Natural Farming Vietnam để được hỗ trợ.",
    successTitle: "Yêu cầu đã được gửi",
    success:
      "Chúng tôi đã ghi nhận xác nhận thanh toán của bạn. Bạn có thể dùng mã bên dưới để tra cứu trạng thái.",
    trackLater: "Tra cứu yêu cầu sau",
    packageUnavailable:
      "Gói hoặc thời hạn này không còn khả dụng. Vui lòng chọn lại.",
    paymentUnavailable:
      "Chuyển khoản đang tạm thời không khả dụng. Vui lòng liên hệ đội ngũ hỗ trợ.",
    duplicate: "Số điện thoại này đang có một yêu cầu mua được xử lý.",
    invalidDetails: "Vui lòng kiểm tra lại số điện thoại và thông tin địa chỉ.",
    notPending: "Yêu cầu này không còn ở trạng thái chờ xác nhận.",
    expired:
      "Yêu cầu mua này đã hết hạn. Vui lòng tạo yêu cầu mới trước khi chuyển khoản.",
    newRequest: "Tạo yêu cầu mới",
    rateLimited: "Bạn thao tác quá nhiều lần. Vui lòng chờ và thử lại sau.",
    genericError: "Không thể hoàn tất yêu cầu. Vui lòng thử lại sau.",
  },
} as const;

export function getCSAPurchaseCopy(locale: Locale) {
  return copy[locale];
}
